"""Add unit_cost to invoice lines and unallocated_amount to payments

Revision ID: 010a2f910027
Revises: 99940d641fee
Create Date: 2025-08-26 14:41:30.620617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '010a2f910027'
down_revision: Union[str, Sequence[str], None] = '99940d641fee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoice_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_invoice_lines_invoice_id'))

    op.drop_table('sales_invoice_lines')
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_allocations_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_payment_allocations_payment_id'))

    op.drop_table('payment_allocations')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_name'))

    op.drop_table('customers')
    with op.batch_alter_table('sales_adjustments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_adjustments_customer_id'))
        batch_op.drop_index(batch_op.f('ix_sales_adjustments_invoice_id'))

    op.drop_table('sales_adjustments')
    with op.batch_alter_table('delivery_note_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_note_lines_dn_id'))
        batch_op.drop_index(batch_op.f('ix_delivery_note_lines_item_id'))

    op.drop_table('delivery_note_lines')
    with op.batch_alter_table('delivery_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_delivery_notes_sales_order_id'))

    op.drop_table('delivery_notes')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_customer_id'))

    op.drop_table('payments')
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_orders_customer_id'))
        batch_op.drop_index(batch_op.f('ix_sales_orders_status'))

    op.drop_table('sales_orders')
    with op.batch_alter_table('sales_order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_item_id'))
        batch_op.drop_index(batch_op.f('ix_sales_order_lines_order_id'))

    op.drop_table('sales_order_lines')
    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_notes_customer_id'))

    op.drop_table('credit_notes')
    with op.batch_alter_table('credit_note_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credit_note_lines_credit_note_id'))

    op.drop_table('credit_note_lines')
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_invoices_customer_id'))
        batch_op.drop_index(batch_op.f('ix_sales_invoices_status'))

    op.drop_table('sales_invoices')
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.alter_column('received_qty',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.alter_column('received_qty',
               existing_type=sa.FLOAT(),
               nullable=True)

    op.create_table('sales_invoices',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('invoice_type', sa.TEXT(), server_default=sa.text("'CREDIT'"), nullable=False),
    sa.Column('subtotal', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_total', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('total', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('balance', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_invoices_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_invoices_customer_id'), ['customer_id'], unique=False)

    op.create_table('credit_note_lines',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('credit_note_id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.TEXT(), nullable=False),
    sa.Column('qty', sa.REAL(), nullable=False),
    sa.Column('unit_price', sa.REAL(), nullable=False),
    sa.Column('tax_rate', sa.REAL(), server_default=sa.text('0'), nullable=True),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('warehouse_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['credit_note_id'], ['credit_notes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_note_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_note_lines_credit_note_id'), ['credit_note_id'], unique=False)

    op.create_table('credit_notes',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('credit_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('reference_invoice_id', sa.INTEGER(), nullable=True),
    sa.Column('subtotal', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('tax_total', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('total', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reference_invoice_id'], ['sales_invoices.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('credit_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credit_notes_customer_id'), ['customer_id'], unique=False)

    op.create_table('sales_order_lines',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.TEXT(), nullable=False),
    sa.Column('ordered_qty', sa.REAL(), nullable=False),
    sa.Column('shipped_qty', sa.REAL(), server_default=sa.text('0'), nullable=False),
    sa.Column('unit_price', sa.REAL(), nullable=False),
    sa.Column('tax_rate', sa.REAL(), server_default=sa.text('0'), nullable=True),
    sa.Column('discount_rate', sa.REAL(), server_default=sa.text('0'), nullable=True),
    sa.Column('warehouse_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_id'], ['sales_orders.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_order_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_order_lines_order_id'), ['order_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_order_lines_item_id'), ['item_id'], unique=False)

    op.create_table('sales_orders',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('order_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_orders_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_orders_customer_id'), ['customer_id'], unique=False)

    op.create_table('payments',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('payment_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('method', sa.TEXT(), nullable=False),
    sa.Column('reference', sa.TEXT(), nullable=True),
    sa.Column('amount', sa.REAL(), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_customer_id'), ['customer_id'], unique=False)

    op.create_table('delivery_notes',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('sales_order_id', sa.INTEGER(), nullable=True),
    sa.Column('delivery_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('status', sa.TEXT(), server_default=sa.text("'DRAFT'"), nullable=False),
    sa.Column('reference', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_orders.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_notes_sales_order_id'), ['sales_order_id'], unique=False)

    op.create_table('delivery_note_lines',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('delivery_note_id', sa.INTEGER(), nullable=False),
    sa.Column('order_line_id', sa.INTEGER(), nullable=True),
    sa.Column('item_id', sa.TEXT(), nullable=False),
    sa.Column('warehouse_id', sa.INTEGER(), nullable=True),
    sa.Column('qty_shipped', sa.REAL(), nullable=False),
    sa.Column('unit_cost', sa.REAL(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_note_id'], ['delivery_notes.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['order_line_id'], ['sales_order_lines.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('delivery_note_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_delivery_note_lines_item_id'), ['item_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_delivery_note_lines_dn_id'), ['delivery_note_id'], unique=False)

    op.create_table('sales_adjustments',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), nullable=True),
    sa.Column('adj_type', sa.TEXT(), nullable=False),
    sa.Column('amount', sa.REAL(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=True),
    sa.Column('adj_date', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_adjustments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_adjustments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_adjustments_customer_id'), ['customer_id'], unique=False)

    op.create_table('customers',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('name', sa.TEXT(), nullable=False),
    sa.Column('email', sa.TEXT(), nullable=True),
    sa.Column('phone', sa.TEXT(), nullable=True),
    sa.Column('terms', sa.TEXT(), nullable=True),
    sa.Column('credit_limit', sa.REAL(), server_default=sa.text('0'), nullable=True),
    sa.Column('is_active', sa.INTEGER(), server_default=sa.text('1'), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_name'), ['name'], unique=1)

    op.create_table('payment_allocations',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('payment_id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_id', sa.INTEGER(), nullable=False),
    sa.Column('amount_applied', sa.REAL(), nullable=False),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_allocations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_allocations_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_allocations_invoice_id'), ['invoice_id'], unique=False)

    op.create_table('sales_invoice_lines',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('invoice_id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.TEXT(), nullable=False),
    sa.Column('qty', sa.REAL(), nullable=False),
    sa.Column('unit_price', sa.REAL(), nullable=False),
    sa.Column('tax_rate', sa.REAL(), server_default=sa.text('0'), nullable=True),
    sa.Column('discount_rate', sa.REAL(), server_default=sa.text('0'), nullable=True),
    sa.Column('warehouse_id', sa.INTEGER(), nullable=True),
    sa.Column('so_line_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['invoice_id'], ['sales_invoices.id'], onupdate='CASCADE', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], onupdate='CASCADE', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['so_line_id'], ['sales_order_lines.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], onupdate='CASCADE', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sales_invoice_lines', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_invoice_lines_invoice_id'), ['invoice_id'], unique=False)

    # ### end Alembic commands ###
