"""Stock reservations and Accounting events

Revision ID: 143d8921d330
Revises: 01ccb8092d98
Create Date: 2025-08-26 15:29:20.656997

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '143d8921d330'
down_revision: Union[str, Sequence[str], None] = '01ccb8092d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    