"""Add JournalBatch model and rewire JournalEntry to it

Revision ID: 19e55437a2fc
Revises: 8f4a61b61658
Create Date: 2025-10-30 14:02:49.048298

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19e55437a2fc'
down_revision: Union[str, Sequence[str], None] = '8f4a61b61658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounting_events', schema=None) as batch_op:
        batch_op.alter_column('batch_no',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               nullable=True)
        batch_op.drop_index(batch_op.f('ix_accounting_events_batch_no'))
        batch_op.create_foreign_key('fk_journal_batches_batch_no', 'journal_batches', ['batch_no'], ['id'])

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_journal_entries_batch_no'), type_='foreignkey')
        batch_op.create_foreign_key('fk_journal_entries_batch_no', 'journal_batches', ['batch_no'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.drop_constraint('fk_journal_entries_batch_no', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_journal_entries_batch_no'), 'accounting_events', ['batch_no'], ['id'])

    with op.batch_alter_table('accounting_events', schema=None) as batch_op:
        batch_op.drop_constraint('fk_journal_batches_batch_no', type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_accounting_events_batch_no'), ['batch_no'], unique=1)
        batch_op.alter_column('batch_no',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###
