"""General Ledger model updates

Revision ID: 1c7918c81f49
Revises: 6c9c115c5b76
Create Date: 2025-09-24 10:40:29.220591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c7918c81f49'
down_revision: Union[str, Sequence[str], None] = '6c9c115c5b76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounting_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_no', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('source_module', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('posted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('reference_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_accounting_events_batch_no'), ['batch_no'], unique=True)
        batch_op.drop_column('event_type')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_no', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('entry_number', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('total_debit', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('total_credit', sa.Numeric(precision=18, scale=2), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(), nullable=True))
        batch_op.alter_column('entry_date',
               existing_type=sa.DATETIME(),
               type_=sa.Date(),
               nullable=False)
        batch_op.drop_index(batch_op.f('ix_journal_entries_reference'))
        batch_op.create_index(batch_op.f('ix_journal_entries_entry_number'), ['entry_number'], unique=False)
        batch_op.create_foreign_key(None, 'accounting_events', ['batch_no'], ['id'])
        batch_op.drop_column('reference')

    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entry_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('account_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('description', sa.String(), nullable=True))
        batch_op.alter_column('debit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
        batch_op.alter_column('credit',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Numeric(precision=18, scale=2),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_journal_lines_account'))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'accounts', ['account_id'], ['code'])
        batch_op.create_foreign_key(None, 'journal_entries', ['entry_id'], ['id'])
        batch_op.drop_column('account')
        batch_op.drop_column('journal_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('journal_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('account', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'journal_entries', ['journal_id'], ['id'])
        batch_op.create_index(batch_op.f('ix_journal_lines_account'), ['account'], unique=False)
        batch_op.alter_column('credit',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.alter_column('debit',
               existing_type=sa.Numeric(precision=18, scale=2),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
        batch_op.drop_column('description')
        batch_op.drop_column('account_id')
        batch_op.drop_column('entry_id')

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reference', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_journal_entries_entry_number'))
        batch_op.create_index(batch_op.f('ix_journal_entries_reference'), ['reference'], unique=False)
        batch_op.alter_column('entry_date',
               existing_type=sa.Date(),
               type_=sa.DATETIME(),
               nullable=True)
        batch_op.drop_column('status')
        batch_op.drop_column('total_credit')
        batch_op.drop_column('total_debit')
        batch_op.drop_column('entry_number')
        batch_op.drop_column('batch_no')

    with op.batch_alter_table('accounting_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type', sa.VARCHAR(), nullable=False))
        batch_op.drop_index(batch_op.f('ix_accounting_events_batch_no'))
        batch_op.alter_column('reference_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('posted_at')
        batch_op.drop_column('description')
        batch_op.drop_column('source_module')
        batch_op.drop_column('batch_no')

    # ### end Alembic commands ###
