"""Stock reservations and Accounting events

Revision ID: 1c8720cadb77
Revises: f52b529351d6
Create Date: 2025-08-26 15:16:19.688514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c8720cadb77'
down_revision: Union[str, Sequence[str], None] = 'f52b529351d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

