"""Accs Events and Reservations

Revision ID: 2a01460d596c
Revises: 567640187baf
Create Date: 2025-08-26 15:43:00.698683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a01460d596c'
down_revision: Union[str, Sequence[str], None] = '567640187baf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
   