"""finance set-up

Revision ID: 3026534538d8
Revises: fff98e936f21
Create Date: 2025-09-18 13:02:45.613364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3026534538d8'
down_revision: Union[str, Sequence[str], None] = 'fff98e936f21'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dimensions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('DEPARTMENT', 'LOCATION', 'PROJECT', 'CUSTOM', name='dimensiontype'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('dimensions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dimensions_id'), ['id'], unique=False)

    op.create_table('reporting_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('statement', sa.Enum('BALANCE_SHEET', 'INCOME_STATEMENT', 'CASH_FLOW', name='reportingstatement'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('reporting_groups', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reporting_groups_id'), ['id'], unique=False)

    op.create_table('accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.Enum('ASSET', 'LIABILITY', 'EQUITY', 'REVENUE', 'EXPENSE', name='accounttype'), nullable=False),
    sa.Column('parent_account_id', sa.Integer(), nullable=True),
    sa.Column('reporting_group_id', sa.Integer(), nullable=True),
    sa.Column('is_control_account', sa.Boolean(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_account_id'], ['accounts.id'], ),
    sa.ForeignKeyConstraint(['reporting_group_id'], ['reporting_groups.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_id'))

    op.drop_table('accounts')
    with op.batch_alter_table('reporting_groups', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reporting_groups_id'))

    op.drop_table('reporting_groups')
    with op.batch_alter_table('dimensions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dimensions_id'))

    op.drop_table('dimensions')
    # ### end Alembic commands ###
