"""Add supplier_id to purchase_orders

Revision ID: 358e36616f7e
Revises: 33abc0f5743c
Create Date: 2025-07-30 16:12:56.972795

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '358e36616f7e'
down_revision: Union[str, Sequence[str], None] = '33abc0f5743c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_in_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_in_progress_id'))

    op.drop_table('work_in_progress')
    with op.batch_alter_table('boms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boms_id'))

    op.drop_table('boms')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('boms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('parent_item_id', sa.INTEGER(), nullable=True),
    sa.Column('component_item_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['component_item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['parent_item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('boms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boms_id'), ['id'], unique=False)

    op.create_table('work_in_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('production_order_id', sa.INTEGER(), nullable=True),
    sa.Column('issued_quantity', sa.FLOAT(), nullable=True),
    sa.Column('completed_quantity', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_in_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_in_progress_id'), ['id'], unique=False)

    # ### end Alembic commands ###
