"""Line total addition

Revision ID: 3f7578019d0f
Revises: 998354d2e2d3
Create Date: 2025-09-12 16:05:05.300731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f7578019d0f'
down_revision: Union[str, Sequence[str], None] = '998354d2e2d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('line_total', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_order_lines', schema=None) as batch_op:
        batch_op.drop_column('line_total')

    # ### end Alembic commands ###
