"""General Ledger Migration fixes

Revision ID: 55ed478e94e0
Revises: c893352bfe61
Create Date: 2025-10-30 11:08:02.364403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '55ed478e94e0'
down_revision: Union[str, Sequence[str], None] = 'c893352bfe61'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounting_events', schema=None) as batch_op:
        batch_op.alter_column('batch_no',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.alter_column('source_module',
               existing_type=sa.VARCHAR(),
               nullable=False)

    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.alter_column('entry_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('entry_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('accounting_events', schema=None) as batch_op:
        batch_op.alter_column('source_module',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('batch_no',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
