"""Additional Accounting and reservation tables

Revision ID: 567640187baf
Revises: 0b43b1964897
Create Date: 2025-08-26 15:40:32.493203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '567640187baf'
down_revision: Union[str, Sequence[str], None] = '0b43b1964897'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    