"""Fixed from the DB

Revision ID: 5755e76ed3ae
Revises: 5b9ce4a2a9e0
Create Date: 2025-08-21 13:45:58.690236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5755e76ed3ae'
down_revision: Union[str, Sequence[str], None] = '5b9ce4a2a9e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('received_qty',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=True)
        

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        
        batch_op.alter_column('received_qty',
               existing_type=sa.FLOAT(),
               server_default=sa.text('0'),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
