"""Are we okay

Revision ID: 57a4d026347b
Revises: 48f4a6b93cce
Create Date: 2025-08-21 14:06:39.297376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57a4d026347b'
down_revision: Union[str, Sequence[str], None] = '48f4a6b93cce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.alter_column('received_qty',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_purchase_order_lines_new_id'))
        batch_op.create_index(batch_op.f('ix_purchase_order_lines_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_lines_id'))
        batch_op.create_index(batch_op.f('ix_purchase_order_lines_new_id'), ['id'], unique=False)
        batch_op.alter_column('received_qty',
               existing_type=sa.FLOAT(),
               server_default=sa.text("'0'"),
               existing_nullable=True)

    # ### end Alembic commands ###
