"""Last update to clear issues

Revision ID: 5e3ebe16422c
Revises: 1f2f2f8d8132
Create Date: 2025-08-21 13:24:42.411226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e3ebe16422c'
down_revision: Union[str, Sequence[str], None] = '1f2f2f8d8132'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('received_qty',
               existing_type=sa.FLOAT(),
               server_default=None,
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_purchase_order_lines_id'), ['id'], unique=False)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_purchase_order_lines_item_id', 'items', ['item_id'], ['item_id'])
        batch_op.create_foreign_key('fk_purchase_order_lines_warehouses_id', 'warehouses', ['warehouse_id'], ['id'])
        batch_op.create_foreign_key('fk_purchase_order_lines_order_id', 'purchase_orders', ['order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.drop_constraint('fk_purchase_order_lines_order_id', type_='foreignkey')
        batch_op.drop_constraint('fk_purchase_order_lines_warehouses_id', type_='foreignkey')
        batch_op.drop_constraint('fk_purchase_order_lines_item_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'items', ['item_id'], ['item_id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'purchase_orders', ['order_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'warehouses', ['warehouse_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
        batch_op.drop_index(batch_op.f('ix_purchase_order_lines_id'))
        batch_op.alter_column('received_qty',
               existing_type=sa.FLOAT(),
               server_default=sa.text('0'),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    # ### end Alembic commands ###
