"""Confirming that payment tables have been updated

Revision ID: 5ece8e67d6e6
Revises: c636cf1d50fb
Create Date: 2025-09-12 12:19:38.719854

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ece8e67d6e6'
down_revision: Union[str, Sequence[str], None] = 'c636cf1d50fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
