"""seed chart of accounts

Revision ID: 6c9c115c5b76
Revises: 3026534538d8
Create Date: 2025-09-18 13:06:39.789188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import orm


# revision identifiers, used by Alembic.
revision: str = '6c9c115c5b76'
down_revision: Union[str, Sequence[str], None] = '3026534538d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    bind = op.get_bind()
    session = orm.Session(bind=bind)
    from backend.seeds.finance_seed import run_seed
    run_seed(session)
    session.close()

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
