"""Add WorkInProgress table

Revision ID: 6fe004a7d07d
Revises: 4f06e7166c97
Create Date: 2025-08-05 14:30:05.807618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fe004a7d07d'
down_revision: Union[str, Sequence[str], None] = '4f06e7166c97'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_in_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_in_progress_id'))

    op.drop_table('work_in_progress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_in_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('production_order_id', sa.INTEGER(), nullable=True),
    sa.Column('issued_quantity', sa.FLOAT(), nullable=True),
    sa.Column('completed_quantity', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('work_in_progress', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_work_in_progress_id'), ['id'], unique=False)

    # ### end Alembic commands ###
