"""add received_qty to purchaseorderline

Revision ID: 920b707b56cb
Revises: 4b7fabd946d9
Create Date: 2025-08-20 20:10:30.282413

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '920b707b56cb'
down_revision: Union[str, Sequence[str], None] = '4b7fabd946d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_boms')
    op.alter_column('boms', 'quantity',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_boms_id'), 'boms', ['id'], unique=False)
    op.alter_column('inventory_logs', 'transaction_id',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('inventory_logs', 'timestamp',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_inventory_logs_id'), 'inventory_logs', ['id'], unique=False)
    op.create_foreign_key('fk_inventory_logs_transaction_id', 'inventory_logs', 'transactions', ['transaction_id'], ['id'])
    op.alter_column('inventory_transactions', 'unit_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_inventory_transactions_id'), 'inventory_transactions', ['id'], unique=False)
    op.alter_column('items', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('items', 'item_id',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               nullable=False)
    op.alter_column('items', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('items', 'average_cost',
               existing_type=sa.REAL(),
               server_default=None,
               type_=sa.Float(),
               existing_nullable=True)
    op.create_index(op.f('ix_items_item_id'), 'items', ['item_id'], unique=True)
    op.create_index(op.f('ix_items_name'), 'items', ['name'], unique=True)
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.create_foreign_key('fk_uoms_id', 'items', 'uoms', ['default_uom_id'], ['id'])
    op.create_foreign_key('fk_warehouses_id', 'items', 'warehouses', ['warehouse_id'], ['id'])
    op.alter_column('production_operations', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('production_operations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_production_operations_id'), 'production_operations', ['id'], unique=False)
    op.alter_column('production_orders', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('production_orders', 'start_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('production_orders', 'end_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_production_orders_id'), 'production_orders', ['id'], unique=False)
    op.add_column('purchase_order_lines', sa.Column('received_qty', sa.Float(), nullable=True))
    op.alter_column('purchase_order_lines', 'quantity',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('purchase_order_lines', 'unit_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               nullable=False)
    op.create_index(op.f('ix_purchase_order_lines_id'), 'purchase_order_lines', ['id'], unique=False)
    op.alter_column('transactions', 'unit_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
    op.alter_column('transactions', 'timestamp',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.alter_column('uom_conversions', 'item_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.create_index(op.f('ix_uom_conversions_id'), 'uom_conversions', ['id'], unique=False)
    op.alter_column('work_in_progress', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('work_in_progress', 'cost_per_unit',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('work_in_progress', 'total_cost',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('work_in_progress', 'status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.create_index(op.f('ix_work_in_progress_id'), 'work_in_progress', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_in_progress_id'), table_name='work_in_progress')
    op.alter_column('work_in_progress', 'status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('work_in_progress', 'total_cost',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('work_in_progress', 'cost_per_unit',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('work_in_progress', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_uom_conversions_id'), table_name='uom_conversions')
    op.alter_column('uom_conversions', 'item_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.alter_column('transactions', 'timestamp',
               existing_type=sa.DateTime(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('transactions', 'unit_cost',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.drop_index(op.f('ix_purchase_order_lines_id'), table_name='purchase_order_lines')
    op.alter_column('purchase_order_lines', 'unit_cost',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
    op.alter_column('purchase_order_lines', 'quantity',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.drop_column('purchase_order_lines', 'received_qty')
    op.drop_index(op.f('ix_production_orders_id'), table_name='production_orders')
    op.alter_column('production_orders', 'end_date',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('production_orders', 'start_date',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('production_orders', 'item_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_index(op.f('ix_production_operations_id'), table_name='production_operations')
    op.alter_column('production_operations', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('production_operations', 'order_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint('fk_warehouses_id', 'items', type_='foreignkey')
    op.drop_constraint('fk_uoms_id', 'items', type_='foreignkey')
    op.create_foreign_key(None, 'items', 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'items', 'uoms', ['default_uom_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_items_name'), table_name='items')
    op.drop_index(op.f('ix_items_item_id'), table_name='items')
    op.alter_column('items', 'average_cost',
               existing_type=sa.Float(),
               server_default=sa.text('(0.0)'),
               type_=sa.REAL(),
               existing_nullable=True)
    op.alter_column('items', 'description',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('items', 'item_id',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('items', 'name',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_index(op.f('ix_inventory_transactions_id'), table_name='inventory_transactions')
    op.alter_column('inventory_transactions', 'unit_cost',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)
    op.drop_constraint('fk_inventory_logs_transaction_id', 'inventory_logs', type_='foreignkey')
    op.drop_index(op.f('ix_inventory_logs_id'), table_name='inventory_logs')
    op.alter_column('inventory_logs', 'timestamp',
               existing_type=sa.DateTime(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
    op.alter_column('inventory_logs', 'transaction_id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_index(op.f('ix_boms_id'), table_name='boms')
    op.alter_column('boms', 'quantity',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
    op.create_table('_alembic_tmp_boms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('parent_item_id', sa.INTEGER(), nullable=True),
    sa.Column('component_item_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['component_item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['parent_item_id'], ['items.item_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
