"""Sales Clean-up

Revision ID: 998354d2e2d3
Revises: 5ece8e67d6e6
Create Date: 2025-09-12 12:49:04.046016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '998354d2e2d3'
down_revision: Union[str, Sequence[str], None] = '5ece8e67d6e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_orders', schema=None) as batch_op:
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###
