"""General Ledger Migrations

Revision ID: bdc68a886045
Revises: 105516df0473
Create Date: 2025-10-30 10:55:42.726192

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdc68a886045'
down_revision: Union[str, Sequence[str], None] = '105516df0473'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounting_events', schema=None) as batch_op:
        batch_op.alter_column('batch_no',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('source_module',
               existing_type=sa.VARCHAR(),
               nullable=True)

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.alter_column('batch_no',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('entry_number',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
        batch_op.alter_column('entry_date',
               existing_type=sa.DATE(),
               nullable=False)

    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.alter_column('entry_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('journal_lines', schema=None) as batch_op:
        batch_op.alter_column('account_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('entry_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('journal_entries', schema=None) as batch_op:
        batch_op.alter_column('entry_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('entry_number',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'0'"),
               existing_nullable=False)
        batch_op.alter_column('batch_no',
               existing_type=sa.INTEGER(),
               server_default=sa.text("'0'"),
               existing_nullable=False)

    with op.batch_alter_table('accounting_events', schema=None) as batch_op:
        batch_op.alter_column('source_module',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('batch_no',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
