"""Payment Tables fixes after importing models

Revision ID: c636cf1d50fb
Revises: aa0692fab1fe
Create Date: 2025-09-12 12:15:02.185823

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c636cf1d50fb'
down_revision: Union[str, Sequence[str], None] = 'aa0692fab1fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
pass

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
