"""Add warehouse_id to purchase order lines

Revision ID: ce1ad27bc5d7
Revises: de236e30ca39
Create Date: 2025-07-30 22:34:06.160971

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce1ad27bc5d7'
down_revision: Union[str, Sequence[str], None] = 'de236e30ca39'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
