"""fix migration with batch alter

Revision ID: d92d027c611f
Revises: 34b89878502c
Create Date: 2025-08-21 10:31:15.824242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd92d027c611f'
down_revision: Union[str, Sequence[str], None] = '34b89878502c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_inventory_logs')
    with op.batch_alter_table('inventory_logs', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_inventory_logs_id'), ['id'], unique=False)
        batch_op.create_foreign_key('fk_inventory_logs_transaction_id', 'transactions', ['transaction_id'], ['id'])

    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_transactions_id'), ['id'], unique=False)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.alter_column('average_cost',
               existing_type=sa.REAL(),
               server_default=None,
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_items_item_id'), ['item_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_items_name'), ['name'], unique=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('fk_uoms_id', 'uoms', ['default_uom_id'], ['id'])
        batch_op.create_foreign_key('fk_warehouses_id', 'warehouses', ['warehouse_id'], ['id'])

    with op.batch_alter_table('production_operations', schema=None) as batch_op:
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_production_operations_id'), ['id'], unique=False)

    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('start_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('end_date',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_production_orders_id'), ['id'], unique=False)

    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.add_column(sa.Column('received_qty', sa.Float(), nullable=True))
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('unit_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               nullable=False)
        batch_op.create_index(batch_op.f('ix_purchase_order_lines_id'), ['id'], unique=False)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('unit_cost',
               existing_type=sa.NUMERIC(precision=12, scale=2),
               type_=sa.Float(),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.TIMESTAMP(),
               server_default=None,
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_transactions_id'), ['id'], unique=False)

    with op.batch_alter_table('uom_conversions', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=sa.TEXT(),
               type_=sa.Integer(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_uom_conversions_id'), ['id'], unique=False)

    with op.batch_alter_table('work_in_progress', schema=None) as batch_op:
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('cost_per_unit',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('total_cost',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_index(batch_op.f('ix_work_in_progress_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('work_in_progress', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_work_in_progress_id'))
        batch_op.alter_column('status',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('total_cost',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('cost_per_unit',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('uom_conversions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_uom_conversions_id'))
        batch_op.alter_column('item_id',
               existing_type=sa.Integer(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_id'))
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('unit_cost',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               existing_nullable=True)

    with op.batch_alter_table('purchase_order_lines', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_purchase_order_lines_id'))
        batch_op.alter_column('unit_cost',
               existing_type=sa.Float(),
               type_=sa.NUMERIC(precision=12, scale=2),
               nullable=True)
        batch_op.alter_column('quantity',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.drop_column('received_qty')

    with op.batch_alter_table('production_orders', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_orders_id'))
        batch_op.alter_column('end_date',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('start_date',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('item_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('production_operations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_production_operations_id'))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.alter_column('order_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('items', schema=None) as batch_op:
        batch_op.drop_constraint('fk_warehouses_id', type_='foreignkey')
        batch_op.drop_constraint('fk_uoms_id', type_='foreignkey')
        batch_op.create_foreign_key(None, 'warehouses', ['warehouse_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'uoms', ['default_uom_id'], ['id'], ondelete='SET NULL')
        batch_op.drop_index(batch_op.f('ix_items_name'))
        batch_op.drop_index(batch_op.f('ix_items_item_id'))
        batch_op.alter_column('average_cost',
               existing_type=sa.REAL(),
               server_default=sa.text('(0.0)'),
               existing_nullable=True)
        batch_op.alter_column('item_id',
               existing_type=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('inventory_transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_transactions_id'))

    with op.batch_alter_table('inventory_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_inventory_logs_transaction_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_inventory_logs_id'))
        batch_op.alter_column('timestamp',
               existing_type=sa.TIMESTAMP(),
               server_default=sa.text('(CURRENT_TIMESTAMP)'),
               existing_nullable=True)

    op.create_table('_alembic_tmp_inventory_logs',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('item_id', sa.INTEGER(), nullable=True),
    sa.Column('warehouse_id', sa.INTEGER(), nullable=True),
    sa.Column('transaction_id', sa.VARCHAR(), nullable=True),
    sa.Column('change', sa.FLOAT(), nullable=True),
    sa.Column('note', sa.VARCHAR(), nullable=True),
    sa.Column('timestamp', sa.TIMESTAMP(), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['items.item_id'], ),
    sa.ForeignKeyConstraint(['transaction_id'], ['transactions.id'], name=op.f('fk_inventory_logs_transaction_id')),
    sa.ForeignKeyConstraint(['warehouse_id'], ['warehouses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
