"""Invoice from Order

Revision ID: e800d559db3e
Revises: 26c461cee953
Create Date: 2025-09-17 13:26:52.010841

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e800d559db3e'
down_revision: Union[str, Sequence[str], None] = '26c461cee953'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.add_column(sa.Column('order_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_sales_invoices_order_id'), ['order_id'], unique=False)
        batch_op.create_foreign_key('fk_sales_orders_order_id', 'sales_orders', ['order_id'], ['id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_invoices', schema=None) as batch_op:
        batch_op.drop_constraint('fk_sales_orders_order_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_sales_invoices_order_id'))
        batch_op.drop_column('order_id')

    # ### end Alembic commands ###
