"""Add missing column

Revision ID: ff3dea3fd50b
Revises: 
Create Date: 2025-07-25 16:21:30.306481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff3dea3fd50b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_in_progress_id'), table_name='work_in_progress')
    op.drop_table('work_in_progress')
    op.drop_index(op.f('ix_boms_id'), table_name='boms')
    op.drop_table('boms')
    op.add_column('uom_conversions', sa.Column('item_id', sa.Integer(), nullable=True))
    op.alter_column('uom_conversions', 'target_uom',
               existing_type=sa.VARCHAR(),
               type_=sa.Integer(),
               existing_nullable=True)
    op.alter_column('uom_conversions', 'factor',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.create_foreign_key(None, 'uom_conversions', 'items', ['item_id'], ['id'])
    op.create_foreign_key(None, 'uom_conversions', 'uoms', ['target_uom'], ['id'])
    op.alter_column('uoms', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('uoms', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('uoms', 'symbol',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('uoms', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'uom_conversions', type_='foreignkey')
    op.drop_constraint(None, 'uom_conversions', type_='foreignkey')
    op.alter_column('uom_conversions', 'factor',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('uom_conversions', 'target_uom',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    op.drop_column('uom_conversions', 'item_id')
    op.drop_constraint(None, 'items', type_='foreignkey')
    op.drop_column('items', 'default_uom_id')
    op.create_table('boms',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('parent_item_id', sa.INTEGER(), nullable=True),
    sa.Column('component_item_id', sa.INTEGER(), nullable=True),
    sa.Column('quantity', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['component_item_id'], ['items.id'], ),
    sa.ForeignKeyConstraint(['parent_item_id'], ['items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_boms_id'), 'boms', ['id'], unique=False)
    op.create_table('work_in_progress',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('production_order_id', sa.INTEGER(), nullable=True),
    sa.Column('issued_quantity', sa.FLOAT(), nullable=True),
    sa.Column('completed_quantity', sa.FLOAT(), nullable=True),
    sa.Column('status', sa.VARCHAR(), nullable=True),
    sa.Column('updated_at', sa.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_in_progress_id'), 'work_in_progress', ['id'], unique=False)
    # ### end Alembic commands ###
